### ISSUE TITLE
thanks bro honestly

### ISSUE THREAD

**Issue by sharpz2003** [l-404-l/emmVRCUnlocker#2]
i know you're having trouble completing this task unlocking the risky function just wanted to say good luck and you are doing amazing

**Comment by l-404-l** [comment]
Not trouble just busy doing other projects don't care much for random shit like this expect on occasion

**Comment by sharpz2003** [comment]
> Not trouble just busy doing other projects don't care much for random shit like this expect on occasion

yh i get you. just keep up this sick work
